# Copyright (C) 2010 Association of Universities for Research in Astronomy(AURA)
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
# 
#     2. Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
# 
#     3. The name of AURA and its representatives may not be used to
#       endorse or promote products derived from this software without
#       specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY AURA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL AURA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.
# 
# 
# 
# Sample configuration for OWL-based HLA ACS Pipeline
# 
# 
# Based on https://www.stsci.edu/svn/hla/software/trunk/FITSProductPipeline/pipesrc/cshrc
# 


# Environment variables that need to be defined for the pipeline scripts.
# Data paths.
export FINAL=/hstdev/project/hla/data/final/
export WORK=/hstdev/project/hla/data/work/
export CAL=/hstdev/project/hla/data/cal/
export RAW=/hstdev/project/hla/data/raw/
export LOG=/hstdev/project/hla/data/log/
export HLA_DATA_PATHS=/hstdev/project/hla/data/:/hstops/project/hla/data/

export DADS=/grp/hst/cdbs/
export REF=${DADS}acs-ref/
export ARCHIVE_DATA=${DADS}acs-raw/
export mtab=${DADS}mtab/
export jref=${REF}
export crotacomp=${DADS}comp/ota/
export cracscomp=${DADS}comp/acs/

export BASEWORK=/hstdev/project/hla/work/
export CONTROL=${BASEWORK}multidrizzle_processing/control/

# Software paths.
export IRAF=/iraf/iraf/
export SOFTWARE=/hstdev/project/hla/bin/
export HLAPipelineBin=${SOFTWARE}
export FITSGeneration=${SOFTWARE}

export hostmachine=`hostname -s`

# Needed for photometric zero point computation.
export crotacomp=${DADS}comp/ota/
export cracscomp=${DADS}comp/acs/
