#
# Sample configuration for OWL-based HLA ACS Pipeline
#
#
# Based on https://www.stsci.edu/svn/hla/software/trunk/FITSProductPipeline/pipesrc/cshrc
#


# Environment variables that need to be defined for the pipeline scripts.
# Data paths.
export FINAL=/hstdev/project/hla/data/final/
export WORK=/hstdev/project/hla/data/work/
export CAL=/hstdev/project/hla/data/cal/
export RAW=/hstdev/project/hla/data/raw/
export LOG=/hstdev/project/hla/data/log/
export HLA_DATA_PATHS=/hstdev/project/hla/data/:/hstops/project/hla/data/

export DADS=/grp/hst/cdbs/
export REF=${DADS}acs-ref/
export ARCHIVE_DATA=${DADS}acs-raw/
export mtab=${DADS}mtab/
export jref=${REF}
export crotacomp=${DADS}comp/ota/
export cracscomp=${DADS}comp/acs/

export BASEWORK=/hstdev/project/hla/work/
export CONTROL=${BASEWORK}multidrizzle_processing/control/

# Software paths.
export IRAF=/iraf/iraf/
export SOFTWARE=/hstdev/project/hla/bin/
export HLAPipelineBin=${SOFTWARE}
export FITSGeneration=${SOFTWARE}

export hostmachine=`hostname -s`

# Needed for photometric zero point computation.
export crotacomp=${DADS}comp/ota/
export cracscomp=${DADS}comp/acs/
